# Generated by Django 4.2.5 on 2024-07-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_remove_comment_driver_rating_passenger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('Not booked', 'Not booked'), ('Booked', 'Booked')], default='Not booked', max_length=100, verbose_name='Статус'),
        ),
    ]
